FROM node:lts-alpine
RUN npm i -g pnpm
WORKDIR /tests
COPY package.json pnpm-lock.yaml ./
RUN pnpm i --frozen-lockfile --unsafe-perm
COPY . .
CMD [ "node_modules/.bin/jest", "--runInBand", "--bail", "--colors" ]
