name: Publish to NPM
inputs:
  npmAuthToken:
    required: true
runs:
  using: composite
  steps:
    - run: |
        echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        yarn publish --non-interactive
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npmAuthToken }}
