services:
  db:
    image: postgres:alpine
    command: -p 8080
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anime_skip_e2e
  prod_backend:
    image: docker.pkg.github.com/anime-skip/backend/api:prod
    depends_on:
      - db
    ports:
      - 8081:8081
    command: sh -c 'sleep 2; /app/api-service'
    env_file: .env.backend
  # staged_backend:
  #   image: docker.pkg.github.com/anime-skip/backend/api:staged
  #   depends_on:
  #     - db
  #   ports:
  #     - 8081:8081
  #   command: sh -c 'sleep 2; /app/api-service'
  #   env_file: .env.backend
