// DO NOT EDIT, THIS IS A GENERATED FILE
// Generated by: src/generate/index.ts

import { GqlResponse, GqlError, StatelessConfig, ApiHealth } from './types';
import { DEFAULT_FETCH } from './fetch';

/**
 * The `Float` scalar type represents signed double-precision fractional values as specified by [IEEE 754](http://en.wikipedia.org/wiki/IEEE_floating_point).
 */
export type GqlFloat = number;

/**
 * Standard [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) timestamp in UTC
 *
 * ### Example
 *
 * ```
 * 2020-08-04T23:43:27Z
 * ```
 */
export type GqlTime = string;

/**
 * The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as "4") or integer (such as 4) input value will be accepted as an ID.
 */
export type GqlID = string;

/**
 * The `String`scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
 */
export type GqlString = string;

/**
 * The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
 */
export type GqlInt = number;

/**
 * The `Boolean` scalar type represents `true` or `false`.
 */
export type GqlBoolean = boolean;

/**
 * Color theme the user prefers
 */
export enum GqlColorTheme {
  /**
   * Change to match where you're watching
   */
  PER_SERVICE = 'PER_SERVICE',
  ANIME_SKIP_BLUE = 'ANIME_SKIP_BLUE',
  VRV_YELLOW = 'VRV_YELLOW',
  FUNIMATION_PURPLE = 'FUNIMATION_PURPLE',
  CRUNCHYROLL_ORANGE = 'CRUNCHYROLL_ORANGE',
}

/**
 * The scope that a template applies to
 */
export enum GqlTemplateType {
  /**
   * The template is loaded for all episodes of a given show
   */
  SHOW = 'SHOW',
  /**
   * The template is loaded for episodes of a given show where their season is included in `Template.seasons`
   */
  SEASONS = 'SEASONS',
}

/**
 * Which of the supported services the `EpisodeUrl` was created for. This is a simple enum that allows
 * for simple checks, but this data can also be pulled from the url in the case of UNKNOWN
 */
export enum GqlEpisodeSource {
  /**
   * Data came from an external source
   */
  UNKNOWN = 'UNKNOWN',
  /**
   * Data is from <vrv.co>
   */
  VRV = 'VRV',
  /**
   * Data is from <funimation.com>
   */
  FUNIMATION = 'FUNIMATION',
}

/**
 * A user's role in the system. Higher roles allow a user write access to certain data that a normal
 * user would not. Some queries and mutations are only alloed by certain roles
 */
export enum GqlRole {
  /**
   * Highest role. Has super user access to all queries and mutations
   */
  DEV = 'DEV',
  /**
   * Administrator role. Has some elevated permissions
   */
  ADMIN = 'ADMIN',
  /**
   * Basic role. Has no elevated permissions
   */
  USER = 'USER',
}

/**
 * Where a timestamp originated from
 */
export enum GqlTimestampSource {
  ANIME_SKIP = 'ANIME_SKIP',
  BETTER_VRV = 'BETTER_VRV',
}

export interface GqlTimestamp {
  id: GqlID;
  createdAt: GqlTime;
  createdByUserId: GqlID;
  createdBy: GqlUser;
  updatedAt: GqlTime;
  updatedByUserId: GqlID;
  updatedBy: GqlUser;
  deletedAt?: GqlTime | undefined;
  deletedByUserId?: GqlID | undefined;
  deletedBy?: GqlUser | undefined;
  at: GqlFloat;
  source: GqlTimestampSource;
  typeId: GqlID;
  type: GqlTimestampType;
  episodeId: GqlID;
  episode: GqlEpisode;
}

/**
 * Data required to create a new `TimestampType`. See `TimestampType` for a description of each field
 */
export interface GqlInputTimestampType {}

/**
 * Data used to update a user's `Preferences`. See `Preferences` for a description of each field. If a
 * field is not passed or passed as `null`, it will leave the value as is and skip updating it
 */
export interface GqlInputPreferences {}

/**
 * A list of users that have elevated permissions when making changes to a show, it's episodes, and
 * timestamps. Show admins are responsible for approving any changes that users might submit.
 *
 * If a user has the `ADMIN` or `DEV` roles, they do not need to be show admins to approve changes or
 * make changes directly. Likewise, if a show doesn't have an admin, the user that create the
 * show/episode will have temporary access to editing the data until someone becomes that shows admin.
 *
 * Admins can be created using the API and will soon come to the Anime Skip player/website.
 */
export interface GqlShowAdmin {
  id: GqlID;
  createdAt: GqlTime;
  createdByUserId: GqlID;
  createdBy: GqlUser;
  updatedAt: GqlTime;
  updatedByUserId: GqlID;
  updatedBy: GqlUser;
  deletedAt?: GqlTime | undefined;
  deletedByUserId?: GqlID | undefined;
  deletedBy?: GqlUser | undefined;
  showId: GqlID;
  show: GqlShow;
  userId: GqlID;
  user: GqlUser;
}

export interface GqlUpdatedTimestamps {
  created: Array<GqlTimestamp>;
  updated: Array<GqlTimestamp>;
  deleted: Array<GqlTimestamp>;
}

/**
 * Episode info provided by a third party. See `Episode` for a description of each field.
 *
 * When creating data based on this type, fill out and post an episode, then timestamps based on the
 * data here. All fields will map 1 to 1 with the exception of `source`. Since a source belongs to a
 * episode for third party data, but belongs to timestamps in Anime Skip, the source should be
 * propogated down to each of the timestamps. This way when more timestamps are added, a episode can
 * have muliple timestamp sources.
 *
 * > Make sure to fill out the `source` field so that original owner of the timestamp is maintained
 */
export interface GqlThirdPartyEpisode {
  id?: GqlID | undefined;
  season?: GqlString | undefined;
  number?: GqlString | undefined;
  absoluteNumber?: GqlString | undefined;
  baseDuration?: GqlFloat | undefined;
  name?: GqlString | undefined;
  source?: GqlTimestampSource | undefined;
  timestamps: Array<GqlThirdPartyTimestamp>;
  showId: GqlString;
  show: GqlThirdPartyShow;
}

/**
 * When no timestamps exist for a specific episode, templates are setup to provide fallback timestamps
 */
export interface GqlTemplate {
  id: GqlID;
  createdAt: GqlTime;
  createdByUserId: GqlID;
  createdBy: GqlUser;
  updatedAt: GqlTime;
  updatedByUserId: GqlID;
  updatedBy: GqlUser;
  deletedAt?: GqlTime | undefined;
  deletedByUserId?: GqlID | undefined;
  deletedBy?: GqlUser | undefined;
  showId: GqlID;
  show: GqlShow;
  type: GqlTemplateType;
  seasons: Array<GqlString>;
  sourceEpisodeId: GqlID;
  sourceEpisode: GqlEpisode;
  timestamps: Array<GqlTimestamp>;
  timestampIds: Array<GqlID>;
}

/**
 * The many to many object that links a timestamp to a template
 */
export interface GqlTemplateTimestamp {
  templateId: GqlID;
  template: GqlTemplate;
  timestampId: GqlID;
  timestamp: GqlTimestamp;
}

/**
 * Data required to modify the timestamps on a template
 */
export interface GqlInputTemplateTimestamp {}

/**
 * When logging in with a password or refresh token, you can get new tokens and account info
 */
export interface GqlLoginData {
  authToken: GqlString;
  refreshToken: GqlString;
  account: GqlAccount;
}

/**
 * Stores information about what where an episode can be watched from
 */
export interface GqlEpisodeUrl {
  url: GqlString;
  createdAt: GqlTime;
  createdByUserId: GqlID;
  createdBy: GqlUser;
  updatedAt: GqlTime;
  updatedByUserId: GqlID;
  updatedBy: GqlUser;
  duration?: GqlFloat | undefined;
  timestampsOffset?: GqlFloat | undefined;
  episodeId: GqlID;
  episode: GqlEpisode;
  source: GqlEpisodeSource;
}

/**
 * Data required to create a new `Episode`. See `Episode` for a description of each field
 */
export interface GqlInputEpisode {}

/**
 * Account info that should only be accessible by the authorised user
 */
export interface GqlAccount {
  id: GqlID;
  createdAt: GqlTime;
  deletedAt?: GqlTime | undefined;
  username: GqlString;
  email: GqlString;
  profileUrl: GqlString;
  adminOfShows: Array<GqlShowAdmin>;
  emailVerified: GqlBoolean;
  role: GqlRole;
  preferences: GqlPreferences;
}

export interface GqlThirdPartyTimestamp {
  id?: GqlID | undefined;
  at: GqlFloat;
  typeId: GqlID;
  type: GqlTimestampType;
}

/**
 * Data required to create a new `Timestamp`. See `Timestamp` for a description of each field
 */
export interface GqlInputTimestamp {}

export interface GqlThirdPartyShow {
  name: GqlString;
  createdAt?: GqlTime | undefined;
  updatedAt?: GqlTime | undefined;
}

export interface GqlInputTimestampOn {}

export interface GqlInputExistingTimestamp {}

/**
 * Basic information about an episode, including season, numbers, a list of timestamps, and urls that
 * it can be watched at
 */
export interface GqlEpisode {
  id: GqlID;
  createdAt: GqlTime;
  createdByUserId: GqlID;
  createdBy: GqlUser;
  updatedAt: GqlTime;
  updatedByUserId: GqlID;
  updatedBy: GqlUser;
  deletedAt?: GqlTime | undefined;
  deletedByUserId?: GqlID | undefined;
  deletedBy?: GqlUser | undefined;
  season?: GqlString | undefined;
  number?: GqlString | undefined;
  absoluteNumber?: GqlString | undefined;
  baseDuration?: GqlFloat | undefined;
  name?: GqlString | undefined;
  show: GqlShow;
  showId: GqlID;
  timestamps: Array<GqlTimestamp>;
  urls: Array<GqlEpisodeUrl>;
  template?: GqlTemplate | undefined;
}

/**
 * Where all the user preferences are stored. This includes what timestamps the user doesn't want to
 * watch
 */
export interface GqlPreferences {
  id: GqlID;
  createdAt: GqlTime;
  updatedAt: GqlTime;
  deletedAt?: GqlTime | undefined;
  userId: GqlID;
  user: GqlUser;
  enableAutoSkip: GqlBoolean;
  enableAutoPlay: GqlBoolean;
  minimizeToolbarWhenEditing: GqlBoolean;
  hideTimelineWhenMinimized: GqlBoolean;
  colorTheme: GqlColorTheme;
  skipBranding: GqlBoolean;
  skipIntros: GqlBoolean;
  skipNewIntros: GqlBoolean;
  skipMixedIntros: GqlBoolean;
  skipRecaps: GqlBoolean;
  skipFiller: GqlBoolean;
  skipCanon: GqlBoolean;
  skipTransitions: GqlBoolean;
  skipCredits: GqlBoolean;
  skipNewCredits: GqlBoolean;
  skipMixedCredits: GqlBoolean;
  skipPreview: GqlBoolean;
  skipTitleCard: GqlBoolean;
}

/**
 * The type a timestamp can be. This table rarely changes so the values fetched can either be hard
 * coded or fetch occasionaly. Anime Skip website and web extension use hardcoded maps to store this
 * data, but a third party might want to fetch and cache this instead since you won't know when Anime
 * Skip adds timestamps
 */
export interface GqlTimestampType {
  id: GqlID;
  createdAt: GqlTime;
  createdByUserId: GqlID;
  createdBy: GqlUser;
  updatedAt: GqlTime;
  updatedByUserId: GqlID;
  updatedBy: GqlUser;
  deletedAt?: GqlTime | undefined;
  deletedByUserId?: GqlID | undefined;
  deletedBy?: GqlUser | undefined;
  name: GqlString;
  description: GqlString;
}

/**
 * Information about a user that is public. See `Account` for a description of each field
 */
export interface GqlUser {
  id: GqlID;
  createdAt: GqlTime;
  deletedAt?: GqlTime | undefined;
  username: GqlString;
  profileUrl: GqlString;
  adminOfShows: Array<GqlShowAdmin>;
}

/**
 * Data required to create a new template. See `Template` for a description of each field
 */
export interface GqlInputTemplate {}

/**
 * Data required to create a new `EpisodeUrl`. See `EpisodeUrl` for a description of each field
 */
export interface GqlInputEpisodeUrl {}

/**
 * The base model has all the fields you would expect a fully fleshed out item in the database would
 * have. It is used to track who create, updated, and deleted items
 */
export interface GqlBaseModel {
  id: GqlID;
  createdAt: GqlTime;
  createdByUserId: GqlID;
  createdBy: GqlUser;
  updatedAt: GqlTime;
  updatedByUserId: GqlID;
  updatedBy: GqlUser;
  deletedAt?: GqlTime | undefined;
  deletedByUserId?: GqlID | undefined;
  deletedBy?: GqlUser | undefined;
}

/**
 * A show containing a list of episodes and relevate links
 */
export interface GqlShow {
  id: GqlID;
  createdAt: GqlTime;
  createdByUserId: GqlID;
  createdBy: GqlUser;
  updatedAt: GqlTime;
  updatedByUserId: GqlID;
  updatedBy: GqlUser;
  deletedAt?: GqlTime | undefined;
  deletedByUserId?: GqlID | undefined;
  deletedBy?: GqlUser | undefined;
  name: GqlString;
  originalName?: GqlString | undefined;
  website?: GqlString | undefined;
  image?: GqlString | undefined;
  admins: Array<GqlShowAdmin>;
  episodes: Array<GqlEpisode>;
  templates: Array<GqlTemplate>;
  seasonCount: GqlInt;
  episodeCount: GqlInt;
}

/**
 * Data required to create a new `Show`. See `Show` for a description of each field
 */
export interface GqlInputShow {}

/**
 * Data required to create a new `ShowAdmin`. See `ShowAdmin` for a description of each field
 */
export interface GqlInputShowAdmin {}

export type StatelessClient = ReturnType<typeof createStatelessClient>;

export function createStatelessClient({
  baseUrl,
  clientId,
  fetch = DEFAULT_FETCH,
}: StatelessConfig) {
  if (fetch == null) throw Error(`fetch was ${fetch}. Did you forget to provide config.fetch?`);

  /**
   * Get the logged in user's private account information
   */
  async function account(query: string, config?: RequestInit): Promise<GqlAccount> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query Account {
  account ${query}
}`,
        operationName: 'Account',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'account', GqlAccount>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['account'];
  }
  /**
   * Use either the username or email and an md5 hash of the user's password to get an access and
   * refresh token
   */
  async function login(
    query: string,
    variables?: { usernameEmail: GqlString; passwordHash: GqlString },
    config?: RequestInit,
  ): Promise<GqlLoginData> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query Login(
  $usernameEmail: String!,
  $passwordHash: String!,
) {
  login(
    usernameEmail: $usernameEmail,
    passwordHash: $passwordHash,
  ) ${query}
}`,
        variables,
        operationName: 'Login',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'login', GqlLoginData>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['login'];
  }
  /**
   * Use a refresh token get a new access and refresh token
   */
  async function loginRefresh(
    query: string,
    variables?: { refreshToken: GqlString },
    config?: RequestInit,
  ): Promise<GqlLoginData> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query LoginRefresh(
  $refreshToken: String!,
) {
  loginRefresh(
    refreshToken: $refreshToken,
  ) ${query}
}`,
        variables,
        operationName: 'LoginRefresh',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'loginRefresh', GqlLoginData>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['loginRefresh'];
  }
  /**
   * Find user with a matching `User.id`
   */
  async function findUser(
    query: string,
    variables?: { userId: GqlID },
    config?: RequestInit,
  ): Promise<GqlUser> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindUser(
  $userId: ID!,
) {
  findUser(
    userId: $userId,
  ) ${query}
}`,
        variables,
        operationName: 'FindUser',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'findUser', GqlUser>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findUser'];
  }
  /**
   * Find user with a matching `User.username`
   */
  async function findUserByUsername(
    query: string,
    variables?: { username: GqlString },
    config?: RequestInit,
  ): Promise<GqlUser> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindUserByUsername(
  $username: String!,
) {
  findUserByUsername(
    username: $username,
  ) ${query}
}`,
        variables,
        operationName: 'FindUserByUsername',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'findUserByUsername', GqlUser>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findUserByUsername'];
  }
  /**
   * Find show with a matching `Show.id`
   */
  async function findShow(
    query: string,
    variables?: { showId: GqlID },
    config?: RequestInit,
  ): Promise<GqlShow> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindShow(
  $showId: ID!,
) {
  findShow(
    showId: $showId,
  ) ${query}
}`,
        variables,
        operationName: 'FindShow',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'findShow', GqlShow>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findShow'];
  }
  /**
   * Search for shows that include the `search` in the `Show.name`. Results are sorted by `Show.name`
   * as `ASC` or `DESC`
   */
  async function searchShows(
    query: string,
    variables?: {
      search?: GqlString | undefined;
      offset?: GqlInt | undefined;
      limit?: GqlInt | undefined;
      sort?: GqlString | undefined;
    },
    config?: RequestInit,
  ): Promise<Array<GqlShow>> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query SearchShows(
  $search: String,
  $offset: Int,
  $limit: Int,
  $sort: String,
) {
  searchShows(
    search: $search,
    offset: $offset,
    limit: $limit,
    sort: $sort,
  ) ${query}
}`,
        variables,
        operationName: 'SearchShows',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'searchShows', Array<GqlShow>>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['searchShows'];
  }
  /**
   * Find show admin with a matching `ShowAdmin.id`
   */
  async function findShowAdmin(
    query: string,
    variables?: { showAdminId: GqlID },
    config?: RequestInit,
  ): Promise<GqlShowAdmin> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindShowAdmin(
  $showAdminId: ID!,
) {
  findShowAdmin(
    showAdminId: $showAdminId,
  ) ${query}
}`,
        variables,
        operationName: 'FindShowAdmin',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'findShowAdmin', GqlShowAdmin>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findShowAdmin'];
  }
  /**
   * Get a list of admins for a given `Show.id`
   */
  async function findShowAdminsByShowId(
    query: string,
    variables?: { showId: GqlID },
    config?: RequestInit,
  ): Promise<Array<GqlShowAdmin>> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindShowAdminsByShowId(
  $showId: ID!,
) {
  findShowAdminsByShowId(
    showId: $showId,
  ) ${query}
}`,
        variables,
        operationName: 'FindShowAdminsByShowId',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'findShowAdminsByShowId',
      Array<GqlShowAdmin>
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findShowAdminsByShowId'];
  }
  /**
   * Get a list of show admins for a given `User.id`
   */
  async function findShowAdminsByUserId(
    query: string,
    variables?: { userId: GqlID },
    config?: RequestInit,
  ): Promise<Array<GqlShowAdmin>> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindShowAdminsByUserId(
  $userId: ID!,
) {
  findShowAdminsByUserId(
    userId: $userId,
  ) ${query}
}`,
        variables,
        operationName: 'FindShowAdminsByUserId',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'findShowAdminsByUserId',
      Array<GqlShowAdmin>
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findShowAdminsByUserId'];
  }
  /**
   * Get a list of recently added episodes that have timestamps.
   *
   * > Since this is a rather intensive query, it is cached for 20 minutes before it will look for new
   * > episodes again
   */
  async function recentlyAddedEpisodes(
    query: string,
    variables?: { limit?: GqlInt | undefined; offset?: GqlInt | undefined },
    config?: RequestInit,
  ): Promise<Array<GqlEpisode>> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query RecentlyAddedEpisodes(
  $limit: Int,
  $offset: Int,
) {
  recentlyAddedEpisodes(
    limit: $limit,
    offset: $offset,
  ) ${query}
}`,
        variables,
        operationName: 'RecentlyAddedEpisodes',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'recentlyAddedEpisodes',
      Array<GqlEpisode>
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['recentlyAddedEpisodes'];
  }
  /**
   * Find episode with a matching `Episode.id`
   */
  async function findEpisode(
    query: string,
    variables?: { episodeId: GqlID },
    config?: RequestInit,
  ): Promise<GqlEpisode> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindEpisode(
  $episodeId: ID!,
) {
  findEpisode(
    episodeId: $episodeId,
  ) ${query}
}`,
        variables,
        operationName: 'FindEpisode',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'findEpisode', GqlEpisode>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findEpisode'];
  }
  /**
   * Get a list of episodes for a given `Show.id`
   */
  async function findEpisodesByShowId(
    query: string,
    variables?: { showId: GqlID },
    config?: RequestInit,
  ): Promise<Array<GqlEpisode>> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindEpisodesByShowId(
  $showId: ID!,
) {
  findEpisodesByShowId(
    showId: $showId,
  ) ${query}
}`,
        variables,
        operationName: 'FindEpisodesByShowId',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'findEpisodesByShowId',
      Array<GqlEpisode>
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findEpisodesByShowId'];
  }
  /**
   * Search for episodes that include the `search` in the `Episode.name`. Results are sorted by
   * `Show.name`as `ASC` or `DESC`
   *
   * Results can be limited to a single show by passing `showId`
   */
  async function searchEpisodes(
    query: string,
    variables?: {
      search?: GqlString | undefined;
      showId?: GqlID | undefined;
      offset?: GqlInt | undefined;
      limit?: GqlInt | undefined;
      sort?: GqlString | undefined;
    },
    config?: RequestInit,
  ): Promise<Array<GqlEpisode>> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query SearchEpisodes(
  $search: String,
  $showId: ID,
  $offset: Int,
  $limit: Int,
  $sort: String,
) {
  searchEpisodes(
    search: $search,
    showId: $showId,
    offset: $offset,
    limit: $limit,
    sort: $sort,
  ) ${query}
}`,
        variables,
        operationName: 'SearchEpisodes',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'searchEpisodes', Array<GqlEpisode>>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['searchEpisodes'];
  }
  /**
   * Get a list of third party episodes for a given `Episode.name`. Since this can return an array of
   * multiple items, always use `findEpisodeUrl` first, then fallback to this query.
   *
   * Current 3rd party timestamp providers include:
   * - [BetterVRV](http://tuckerchap.in/BetterVRV/)
   *
   * > See `ThirdPartyEpisode` for more information about how to create data based on this type
   */
  async function findEpisodeByName(
    query: string,
    variables?: { name: GqlString },
    config?: RequestInit,
  ): Promise<Array<GqlThirdPartyEpisode>> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindEpisodeByName(
  $name: String!,
) {
  findEpisodeByName(
    name: $name,
  ) ${query}
}`,
        variables,
        operationName: 'FindEpisodeByName',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'findEpisodeByName',
      Array<GqlThirdPartyEpisode>
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findEpisodeByName'];
  }
  /**
   * Find an episode based on a URL. This is the primary method used to lookup data for a known service
   * URL. See `findEpisodeByName` for looking up fallback data.
   */
  async function findEpisodeUrl(
    query: string,
    variables?: { episodeUrl: GqlString },
    config?: RequestInit,
  ): Promise<GqlEpisodeUrl> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindEpisodeUrl(
  $episodeUrl: String!,
) {
  findEpisodeUrl(
    episodeUrl: $episodeUrl,
  ) ${query}
}`,
        variables,
        operationName: 'FindEpisodeUrl',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'findEpisodeUrl', GqlEpisodeUrl>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findEpisodeUrl'];
  }
  /**
   * List all the `EpisodeUrl`s for a given `Episode.id`
   */
  async function findEpisodeUrlsByEpisodeId(
    query: string,
    variables?: { episodeId: GqlID },
    config?: RequestInit,
  ): Promise<Array<GqlEpisodeUrl>> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindEpisodeUrlsByEpisodeId(
  $episodeId: ID!,
) {
  findEpisodeUrlsByEpisodeId(
    episodeId: $episodeId,
  ) ${query}
}`,
        variables,
        operationName: 'FindEpisodeUrlsByEpisodeId',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'findEpisodeUrlsByEpisodeId',
      Array<GqlEpisodeUrl>
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findEpisodeUrlsByEpisodeId'];
  }
  /**
   * Get timestamp info based on a `Timestamp.id`
   */
  async function findTimestamp(
    query: string,
    variables?: { timestampId: GqlID },
    config?: RequestInit,
  ): Promise<GqlTimestamp> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindTimestamp(
  $timestampId: ID!,
) {
  findTimestamp(
    timestampId: $timestampId,
  ) ${query}
}`,
        variables,
        operationName: 'FindTimestamp',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'findTimestamp', GqlTimestamp>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findTimestamp'];
  }
  /**
   * Get all the timestamps for an episode
   */
  async function findTimestampsByEpisodeId(
    query: string,
    variables?: { episodeId: GqlID },
    config?: RequestInit,
  ): Promise<Array<GqlTimestamp>> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindTimestampsByEpisodeId(
  $episodeId: ID!,
) {
  findTimestampsByEpisodeId(
    episodeId: $episodeId,
  ) ${query}
}`,
        variables,
        operationName: 'FindTimestampsByEpisodeId',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'findTimestampsByEpisodeId',
      Array<GqlTimestamp>
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findTimestampsByEpisodeId'];
  }
  /**
   * Get timestamp type info based on a `TimestampType.id`
   */
  async function findTimestampType(
    query: string,
    variables?: { timestampTypeId: GqlID },
    config?: RequestInit,
  ): Promise<GqlTimestampType> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindTimestampType(
  $timestampTypeId: ID!,
) {
  findTimestampType(
    timestampTypeId: $timestampTypeId,
  ) ${query}
}`,
        variables,
        operationName: 'FindTimestampType',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'findTimestampType',
      GqlTimestampType
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findTimestampType'];
  }
  /**
   * List all the `TimestampType`s. Items come back in a random order
   */
  async function allTimestampTypes(
    query: string,
    config?: RequestInit,
  ): Promise<Array<GqlTimestampType>> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query AllTimestampTypes {
  allTimestampTypes ${query}
}`,
        operationName: 'AllTimestampTypes',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'allTimestampTypes',
      Array<GqlTimestampType>
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['allTimestampTypes'];
  }
  /**
   * Get template info based on a `Template.id`
   */
  async function findTemplate(
    query: string,
    variables?: { templateId: GqlID },
    config?: RequestInit,
  ): Promise<GqlTemplate> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindTemplate(
  $templateId: ID!,
) {
  findTemplate(
    templateId: $templateId,
  ) ${query}
}`,
        variables,
        operationName: 'FindTemplate',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'findTemplate', GqlTemplate>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findTemplate'];
  }
  /**
   * Get a list of templates based on the `Template.showId`
   */
  async function findTemplatesByShowId(
    query: string,
    variables?: { showId: GqlID },
    config?: RequestInit,
  ): Promise<Array<GqlTemplate>> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindTemplatesByShowId(
  $showId: ID!,
) {
  findTemplatesByShowId(
    showId: $showId,
  ) ${query}
}`,
        variables,
        operationName: 'FindTemplatesByShowId',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'findTemplatesByShowId',
      Array<GqlTemplate>
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findTemplatesByShowId'];
  }
  /**
   * Find the most relevant template based on a few search criteria. If multiple templates are found,
   * their priority is like so:
   *
   * 1. Matching `sourceEpisodeID`
   * 2. Matching show name (case sensitive) and season (case sensitive)
   * 3. Matching show name (case sensitive)
   */
  async function findTemplateByDetails(
    query: string,
    variables?: {
      episodeId?: GqlID | undefined;
      showName?: GqlString | undefined;
      season?: GqlString | undefined;
    },
    config?: RequestInit,
  ): Promise<GqlTemplate> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `query FindTemplateByDetails(
  $episodeId: ID,
  $showName: String,
  $season: String,
) {
  findTemplateByDetails(
    episodeId: $episodeId,
    showName: $showName,
    season: $season,
  ) ${query}
}`,
        variables,
        operationName: 'FindTemplateByDetails',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'findTemplateByDetails',
      GqlTemplate
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['findTemplateByDetails'];
  }
  /**
   * Create a user account. 3rd party applications will not have access to this function because of
   * `recaptchaResponse`. Redirect new users to create an account on <anime-skip.com>
   */
  async function createAccount(
    query: string,
    variables?: {
      username: GqlString;
      email: GqlString;
      passwordHash: GqlString;
      recaptchaResponse: GqlString;
    },
    config?: RequestInit,
  ): Promise<GqlLoginData> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation CreateAccount(
  $username: String!,
  $email: String!,
  $passwordHash: String!,
  $recaptchaResponse: String!,
) {
  createAccount(
    username: $username,
    email: $email,
    passwordHash: $passwordHash,
    recaptchaResponse: $recaptchaResponse,
  ) ${query}
}`,
        variables,
        operationName: 'CreateAccount',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'createAccount', GqlLoginData>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['createAccount'];
  }
  /**
   * Change a user's password by first confirming the old one. This is not a forgot password flow
   *
   * > Note the passwords aren't md5 hashes. The regular login will be moving to this as well eventually
   */
  async function changePassword(
    query: string,
    variables?: { oldPassword: GqlString; newPassword: GqlString; confirmNewPassword: GqlString },
    config?: RequestInit,
  ): Promise<GqlLoginData> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation ChangePassword(
  $oldPassword: String!,
  $newPassword: String!,
  $confirmNewPassword: String!,
) {
  changePassword(
    oldPassword: $oldPassword,
    newPassword: $newPassword,
    confirmNewPassword: $confirmNewPassword,
  ) ${query}
}`,
        variables,
        operationName: 'ChangePassword',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'changePassword', GqlLoginData>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['changePassword'];
  }
  /**
   * Resend the verification email for the account of the authenticated user
   */
  async function resendVerificationEmail(
    query: string,
    variables?: { recaptchaResponse: GqlString },
    config?: RequestInit,
  ): Promise<GqlBoolean | undefined> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation ResendVerificationEmail(
  $recaptchaResponse: String!,
) {
  resendVerificationEmail(
    recaptchaResponse: $recaptchaResponse,
  ) ${query}
}`,
        variables,
        operationName: 'ResendVerificationEmail',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'resendVerificationEmail',
      GqlBoolean | undefined
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['resendVerificationEmail'];
  }
  /**
   * Callback to handle the verification token included in the email sent using
   * `resendVerificationEmail`
   */
  async function verifyEmailAddress(
    query: string,
    variables?: { validationToken: GqlString },
    config?: RequestInit,
  ): Promise<GqlAccount> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation VerifyEmailAddress(
  $validationToken: String!,
) {
  verifyEmailAddress(
    validationToken: $validationToken,
  ) ${query}
}`,
        variables,
        operationName: 'VerifyEmailAddress',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'verifyEmailAddress', GqlAccount>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['verifyEmailAddress'];
  }
  /**
   * The first step in the password reset process
   *
   * It sends an email containing a link to reset your password with. That link includes a token, the
   * `passwordResetToken`, that can be passed into the `resetPassword` mutation.
   *
   * > Because the `recaptchaResponse` is required, this can not be performed by 3rd parties
   */
  async function requestPasswordReset(
    query: string,
    variables?: { recaptchaResponse: GqlString; email: GqlString },
    config?: RequestInit,
  ): Promise<GqlBoolean> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation RequestPasswordReset(
  $recaptchaResponse: String!,
  $email: String!,
) {
  requestPasswordReset(
    recaptchaResponse: $recaptchaResponse,
    email: $email,
  ) ${query}
}`,
        variables,
        operationName: 'RequestPasswordReset',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'requestPasswordReset', GqlBoolean>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['requestPasswordReset'];
  }
  /**
   * The second step in the password reset process, coming after `requestPasswordReset`
   *
   * This step is pretty self explanatory, this is when the password is actually reset for a user
   */
  async function resetPassword(
    query: string,
    variables?: {
      passwordResetToken: GqlString;
      newPassword: GqlString;
      confirmNewPassword: GqlString;
    },
    config?: RequestInit,
  ): Promise<GqlLoginData> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation ResetPassword(
  $passwordResetToken: String!,
  $newPassword: String!,
  $confirmNewPassword: String!,
) {
  resetPassword(
    passwordResetToken: $passwordResetToken,
    newPassword: $newPassword,
    confirmNewPassword: $confirmNewPassword,
  ) ${query}
}`,
        variables,
        operationName: 'ResetPassword',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'resetPassword', GqlLoginData>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['resetPassword'];
  }
  /**
   * Request your account be deleted. The user will receive an email with a link to confirm deleting
   * their account
   */
  async function deleteAccountRequest(
    query: string,
    variables?: { passwordHash: GqlString },
    config?: RequestInit,
  ): Promise<GqlAccount> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation DeleteAccountRequest(
  $passwordHash: String!,
) {
  deleteAccountRequest(
    passwordHash: $passwordHash,
  ) ${query}
}`,
        variables,
        operationName: 'DeleteAccountRequest',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'deleteAccountRequest', GqlAccount>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['deleteAccountRequest'];
  }
  /**
   * Handle a deleteToken from `deleteAccountRequest` and actually delete the user's account
   */
  async function deleteAccount(
    query: string,
    variables?: { deleteToken: GqlString },
    config?: RequestInit,
  ): Promise<GqlAccount> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation DeleteAccount(
  $deleteToken: String!,
) {
  deleteAccount(
    deleteToken: $deleteToken,
  ) ${query}
}`,
        variables,
        operationName: 'DeleteAccount',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'deleteAccount', GqlAccount>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['deleteAccount'];
  }
  /**
   * Update user preferences
   */
  async function savePreferences(
    query: string,
    variables?: { preferences: GqlInputPreferences },
    config?: RequestInit,
  ): Promise<GqlPreferences> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation SavePreferences(
  $preferences: InputPreferences!,
) {
  savePreferences(
    preferences: $preferences,
  ) ${query}
}`,
        variables,
        operationName: 'SavePreferences',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'savePreferences', GqlPreferences>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['savePreferences'];
  }
  /**
   * Create a show and optionally become an admin
   */
  async function createShow(
    query: string,
    variables?: { showInput: GqlInputShow; becomeAdmin: GqlBoolean },
    config?: RequestInit,
  ): Promise<GqlShow> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation CreateShow(
  $showInput: InputShow!,
  $becomeAdmin: Boolean!,
) {
  createShow(
    showInput: $showInput,
    becomeAdmin: $becomeAdmin,
  ) ${query}
}`,
        variables,
        operationName: 'CreateShow',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'createShow', GqlShow>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['createShow'];
  }
  /**
   * Update show data
   *
   * > `@isShowAdmin` - You need to be an admin of the show to do this action
   */
  async function updateShow(
    query: string,
    variables?: { showId: GqlID; newShow: GqlInputShow },
    config?: RequestInit,
  ): Promise<GqlShow> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation UpdateShow(
  $showId: ID!,
  $newShow: InputShow!,
) {
  updateShow(
    showId: $showId,
    newShow: $newShow,
  ) ${query}
}`,
        variables,
        operationName: 'UpdateShow',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'updateShow', GqlShow>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['updateShow'];
  }
  /**
   * Delete a show and all it's children (episodes, episode urls, timestamps, admins, etc)
   *
   * > `@hasRole(role: ADMIN)` - The user must have the `ADMIN` role to perform this action
   */
  async function deleteShow(
    query: string,
    variables?: { showId: GqlID },
    config?: RequestInit,
  ): Promise<GqlShow> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation DeleteShow(
  $showId: ID!,
) {
  deleteShow(
    showId: $showId,
  ) ${query}
}`,
        variables,
        operationName: 'DeleteShow',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'deleteShow', GqlShow>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['deleteShow'];
  }
  /**
   * Give admin privilege to a user for a show.
   *
   * > `@isShowAdmin` - You need to be an admin of the show to do this action
   */
  async function createShowAdmin(
    query: string,
    variables?: { showAdminInput: GqlInputShowAdmin },
    config?: RequestInit,
  ): Promise<GqlShowAdmin> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation CreateShowAdmin(
  $showAdminInput: InputShowAdmin!,
) {
  createShowAdmin(
    showAdminInput: $showAdminInput,
  ) ${query}
}`,
        variables,
        operationName: 'CreateShowAdmin',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'createShowAdmin', GqlShowAdmin>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['createShowAdmin'];
  }
  /**
   * Remove admin privileges from a user for a show.
   *
   * > `@isShowAdmin` - You need to be an admin of the show to do this action
   */
  async function deleteShowAdmin(
    query: string,
    variables?: { showAdminId: GqlID },
    config?: RequestInit,
  ): Promise<GqlShowAdmin> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation DeleteShowAdmin(
  $showAdminId: ID!,
) {
  deleteShowAdmin(
    showAdminId: $showAdminId,
  ) ${query}
}`,
        variables,
        operationName: 'DeleteShowAdmin',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'deleteShowAdmin', GqlShowAdmin>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['deleteShowAdmin'];
  }
  /**
   * Create an episode under a `Show`
   *
   * > `@isShowAdmin` - You need to be an admin of the show to do this action
   */
  async function createEpisode(
    query: string,
    variables?: { showId: GqlID; episodeInput: GqlInputEpisode },
    config?: RequestInit,
  ): Promise<GqlEpisode> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation CreateEpisode(
  $showId: ID!,
  $episodeInput: InputEpisode!,
) {
  createEpisode(
    showId: $showId,
    episodeInput: $episodeInput,
  ) ${query}
}`,
        variables,
        operationName: 'CreateEpisode',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'createEpisode', GqlEpisode>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['createEpisode'];
  }
  /**
   * Update episode info
   *
   * > `@isShowAdmin` - You need to be an admin of the show to do this action
   */
  async function updateEpisode(
    query: string,
    variables?: { episodeId: GqlID; newEpisode: GqlInputEpisode },
    config?: RequestInit,
  ): Promise<GqlEpisode> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation UpdateEpisode(
  $episodeId: ID!,
  $newEpisode: InputEpisode!,
) {
  updateEpisode(
    episodeId: $episodeId,
    newEpisode: $newEpisode,
  ) ${query}
}`,
        variables,
        operationName: 'UpdateEpisode',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'updateEpisode', GqlEpisode>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['updateEpisode'];
  }
  /**
   * Delete an episode and all it's child data
   *
   * > `@isShowAdmin` - You need to be an admin of the show to do this action
   */
  async function deleteEpisode(
    query: string,
    variables?: { episodeId: GqlID },
    config?: RequestInit,
  ): Promise<GqlEpisode> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation DeleteEpisode(
  $episodeId: ID!,
) {
  deleteEpisode(
    episodeId: $episodeId,
  ) ${query}
}`,
        variables,
        operationName: 'DeleteEpisode',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'deleteEpisode', GqlEpisode>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['deleteEpisode'];
  }
  /**
   * Link an `Episode` to a service URL
   *
   * > `@isShowAdmin` - You need to be an admin of the show to do this action
   */
  async function createEpisodeUrl(
    query: string,
    variables?: { episodeId: GqlID; episodeUrlInput: GqlInputEpisodeUrl },
    config?: RequestInit,
  ): Promise<GqlEpisodeUrl> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation CreateEpisodeUrl(
  $episodeId: ID!,
  $episodeUrlInput: InputEpisodeUrl!,
) {
  createEpisodeUrl(
    episodeId: $episodeId,
    episodeUrlInput: $episodeUrlInput,
  ) ${query}
}`,
        variables,
        operationName: 'CreateEpisodeUrl',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'createEpisodeUrl', GqlEpisodeUrl>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['createEpisodeUrl'];
  }
  /**
   * Unlink an `Episode` to from service URL
   *
   * > `@isShowAdmin` - You need to be an admin of the show to do this action
   */
  async function deleteEpisodeUrl(
    query: string,
    variables?: { episodeUrl: GqlString },
    config?: RequestInit,
  ): Promise<GqlEpisodeUrl> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation DeleteEpisodeUrl(
  $episodeUrl: String!,
) {
  deleteEpisodeUrl(
    episodeUrl: $episodeUrl,
  ) ${query}
}`,
        variables,
        operationName: 'DeleteEpisodeUrl',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'deleteEpisodeUrl', GqlEpisodeUrl>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['deleteEpisodeUrl'];
  }
  /**
   * Update episode url info
   *
   * > `@isShowAdmin` - You need to be an admin of the show to do this action
   */
  async function updateEpisodeUrl(
    query: string,
    variables?: { episodeUrl: GqlString; newEpisodeUrl: GqlInputEpisodeUrl },
    config?: RequestInit,
  ): Promise<GqlEpisodeUrl> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation UpdateEpisodeUrl(
  $episodeUrl: String!,
  $newEpisodeUrl: InputEpisodeUrl!,
) {
  updateEpisodeUrl(
    episodeUrl: $episodeUrl,
    newEpisodeUrl: $newEpisodeUrl,
  ) ${query}
}`,
        variables,
        operationName: 'UpdateEpisodeUrl',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'updateEpisodeUrl', GqlEpisodeUrl>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['updateEpisodeUrl'];
  }
  /**
   * Add a timestamp to an `Episode`
   *
   * > `@isShowAdmin` - You need to be an admin of the show to do this action
   */
  async function createTimestamp(
    query: string,
    variables?: { episodeId: GqlID; timestampInput: GqlInputTimestamp },
    config?: RequestInit,
  ): Promise<GqlTimestamp> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation CreateTimestamp(
  $episodeId: ID!,
  $timestampInput: InputTimestamp!,
) {
  createTimestamp(
    episodeId: $episodeId,
    timestampInput: $timestampInput,
  ) ${query}
}`,
        variables,
        operationName: 'CreateTimestamp',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'createTimestamp', GqlTimestamp>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['createTimestamp'];
  }
  /**
   * Update timestamp data
   *
   * > `@isShowAdmin` - You need to be an admin of the show to do this action
   */
  async function updateTimestamp(
    query: string,
    variables?: { timestampId: GqlID; newTimestamp: GqlInputTimestamp },
    config?: RequestInit,
  ): Promise<GqlTimestamp> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation UpdateTimestamp(
  $timestampId: ID!,
  $newTimestamp: InputTimestamp!,
) {
  updateTimestamp(
    timestampId: $timestampId,
    newTimestamp: $newTimestamp,
  ) ${query}
}`,
        variables,
        operationName: 'UpdateTimestamp',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'updateTimestamp', GqlTimestamp>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['updateTimestamp'];
  }
  /**
   * Delete a timestamp
   *
   * > `@isShowAdmin` - You need to be an admin of the show to do this action
   */
  async function deleteTimestamp(
    query: string,
    variables?: { timestampId: GqlID },
    config?: RequestInit,
  ): Promise<GqlTimestamp> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation DeleteTimestamp(
  $timestampId: ID!,
) {
  deleteTimestamp(
    timestampId: $timestampId,
  ) ${query}
}`,
        variables,
        operationName: 'DeleteTimestamp',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'deleteTimestamp', GqlTimestamp>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['deleteTimestamp'];
  }
  /**
   * Will create, update, and delete timestamps as passed. Partial failures are completely rolled back
   *
   * > `@isShowAdmin` - You need to be an admin of the show to do this action
   */
  async function updateTimestamps(
    query: string,
    variables?: {
      create: Array<GqlInputTimestampOn>;
      update: Array<GqlInputExistingTimestamp>;
      delete_: Array<GqlID>;
    },
    config?: RequestInit,
  ): Promise<GqlUpdatedTimestamps> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation UpdateTimestamps(
  $create: [InputTimestampOn!]!,
  $update: [InputExistingTimestamp!]!,
  $delete: [ID!]!,
) {
  updateTimestamps(
    create: $create,
    update: $update,
    delete: $delete,
  ) ${query}
}`,
        variables,
        operationName: 'UpdateTimestamps',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'updateTimestamps',
      GqlUpdatedTimestamps
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['updateTimestamps'];
  }
  /**
   * Create a timestamp type
   *
   * > `@hasRole(role: ADMIN)` - The user must have the `ADMIN` role to perform this action
   */
  async function createTimestampType(
    query: string,
    variables?: { timestampTypeInput: GqlInputTimestampType },
    config?: RequestInit,
  ): Promise<GqlTimestampType> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation CreateTimestampType(
  $timestampTypeInput: InputTimestampType!,
) {
  createTimestampType(
    timestampTypeInput: $timestampTypeInput,
  ) ${query}
}`,
        variables,
        operationName: 'CreateTimestampType',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'createTimestampType',
      GqlTimestampType
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['createTimestampType'];
  }
  /**
   * Update a timestamp type
   *
   * > `@hasRole(role: ADMIN)` - The user must have the `ADMIN` role to perform this action
   */
  async function updateTimestampType(
    query: string,
    variables?: { timestampTypeId: GqlID; newTimestampType: GqlInputTimestampType },
    config?: RequestInit,
  ): Promise<GqlTimestampType> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation UpdateTimestampType(
  $timestampTypeId: ID!,
  $newTimestampType: InputTimestampType!,
) {
  updateTimestampType(
    timestampTypeId: $timestampTypeId,
    newTimestampType: $newTimestampType,
  ) ${query}
}`,
        variables,
        operationName: 'UpdateTimestampType',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'updateTimestampType',
      GqlTimestampType
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['updateTimestampType'];
  }
  /**
   * Delete a timestamp type
   *
   * > `@hasRole(role: ADMIN)` - The user must have the `ADMIN` role to perform this action
   */
  async function deleteTimestampType(
    query: string,
    variables?: { timestampTypeId: GqlID },
    config?: RequestInit,
  ): Promise<GqlTimestampType> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation DeleteTimestampType(
  $timestampTypeId: ID!,
) {
  deleteTimestampType(
    timestampTypeId: $timestampTypeId,
  ) ${query}
}`,
        variables,
        operationName: 'DeleteTimestampType',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'deleteTimestampType',
      GqlTimestampType
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['deleteTimestampType'];
  }
  /**
   * Make changes to an existing template
   */
  async function createTemplate(
    query: string,
    variables?: { newTemplate: GqlInputTemplate },
    config?: RequestInit,
  ): Promise<GqlTemplate> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation CreateTemplate(
  $newTemplate: InputTemplate!,
) {
  createTemplate(
    newTemplate: $newTemplate,
  ) ${query}
}`,
        variables,
        operationName: 'CreateTemplate',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'createTemplate', GqlTemplate>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['createTemplate'];
  }
  /**
   * Make changes to an existing template
   */
  async function updateTemplate(
    query: string,
    variables?: { templateId: GqlID; newTemplate: GqlInputTemplate },
    config?: RequestInit,
  ): Promise<GqlTemplate> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation UpdateTemplate(
  $templateId: ID!,
  $newTemplate: InputTemplate!,
) {
  updateTemplate(
    templateId: $templateId,
    newTemplate: $newTemplate,
  ) ${query}
}`,
        variables,
        operationName: 'UpdateTemplate',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'updateTemplate', GqlTemplate>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['updateTemplate'];
  }
  /**
   * Delete an existing template
   */
  async function deleteTemplate(
    query: string,
    variables?: { templateId: GqlID },
    config?: RequestInit,
  ): Promise<GqlTemplate> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation DeleteTemplate(
  $templateId: ID!,
) {
  deleteTemplate(
    templateId: $templateId,
  ) ${query}
}`,
        variables,
        operationName: 'DeleteTemplate',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<'deleteTemplate', GqlTemplate>;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['deleteTemplate'];
  }
  /**
   * Add a timestamp to an existing template
   */
  async function addTimestampToTemplate(
    query: string,
    variables?: { templateTimestamp: GqlInputTemplateTimestamp },
    config?: RequestInit,
  ): Promise<GqlTemplateTimestamp> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation AddTimestampToTemplate(
  $templateTimestamp: InputTemplateTimestamp!,
) {
  addTimestampToTemplate(
    templateTimestamp: $templateTimestamp,
  ) ${query}
}`,
        variables,
        operationName: 'AddTimestampToTemplate',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'addTimestampToTemplate',
      GqlTemplateTimestamp
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['addTimestampToTemplate'];
  }
  /**
   * Remove a timestamp from an existing template
   */
  async function removeTimestampFromTemplate(
    query: string,
    variables?: { templateTimestamp: GqlInputTemplateTimestamp },
    config?: RequestInit,
  ): Promise<GqlTemplateTimestamp> {
    const res = await fetch(baseUrl + '/graphql', {
      ...config,
      method: 'POST',
      body: JSON.stringify({
        query: `mutation RemoveTimestampFromTemplate(
  $templateTimestamp: InputTemplateTimestamp!,
) {
  removeTimestampFromTemplate(
    templateTimestamp: $templateTimestamp,
  ) ${query}
}`,
        variables,
        operationName: 'RemoveTimestampFromTemplate',
      }),
      headers: {
        ...config?.headers,
        'X-Client-ID': clientId,
        'Content-Type': 'application/json',
      },
    });
    const { data, errors } = (await res.json()) as GqlResponse<
      'removeTimestampFromTemplate',
      GqlTemplateTimestamp
    >;
    if (errors != null) throw new GqlError(res.status, errors);
    return data['removeTimestampFromTemplate'];
  }

  async function healthCheck(): Promise<ApiHealth> {
    const res = await fetch(baseUrl + '/status', { headers: { 'X-Client-ID': clientId } });
    const payload = await res.json();
    const { errors } = payload;
    if (errors != null) throw new GqlError(res.status, errors);
    return payload;
  }
  return {
    account,
    login,
    loginRefresh,
    findUser,
    findUserByUsername,
    findShow,
    searchShows,
    findShowAdmin,
    findShowAdminsByShowId,
    findShowAdminsByUserId,
    recentlyAddedEpisodes,
    findEpisode,
    findEpisodesByShowId,
    searchEpisodes,
    findEpisodeByName,
    findEpisodeUrl,
    findEpisodeUrlsByEpisodeId,
    findTimestamp,
    findTimestampsByEpisodeId,
    findTimestampType,
    allTimestampTypes,
    findTemplate,
    findTemplatesByShowId,
    findTemplateByDetails,
    createAccount,
    changePassword,
    resendVerificationEmail,
    verifyEmailAddress,
    requestPasswordReset,
    resetPassword,
    deleteAccountRequest,
    deleteAccount,
    savePreferences,
    createShow,
    updateShow,
    deleteShow,
    createShowAdmin,
    deleteShowAdmin,
    createEpisode,
    updateEpisode,
    deleteEpisode,
    createEpisodeUrl,
    deleteEpisodeUrl,
    updateEpisodeUrl,
    createTimestamp,
    updateTimestamp,
    deleteTimestamp,
    updateTimestamps,
    createTimestampType,
    updateTimestampType,
    deleteTimestampType,
    createTemplate,
    updateTemplate,
    deleteTemplate,
    addTimestampToTemplate,
    removeTimestampFromTemplate,
    healthCheck,
  };
}
