import CodeBlockWriter from 'code-block-writer';

export function createTsWriter(): CodeBlockWriter {
  const w = new CodeBlockWriter({
    useSingleQuote: true,
    indentNumberOfSpaces: 2,
  });
  w.writeLine('// DO NOT EDIT, THIS IS A GENERATED FILE');
  w.writeLine('// Generated by: src/generate/index.ts');
  w.blankLine();
  return w;
}
