name: Verify Code
runs:
  using: composite
  steps:
    - run: |
        pnpm compile
        pnpm lint:no-fix
        pnpm format:check
        pnpm build
      shell: bash
    - run: |
        if [[ "$(git diff --stat)" != "" ]]; then
          echo "Generated files are out of date. Run `pnpm gen` to regenerate them. Diff:"
          git diff
          exit 1
        fi
      shell: bash
