name: Publish
on:
  release:
    types: [created, updated]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@anime-skip'
      - run: yarn install
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
      - run: npm run build
      - run: npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
